apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-webapp1
  namespace: ns1
spec:
 scaleTargetRef:
   apiVersion: "apps/v1"
   kind: Deployment
   name: webapp1-deployment
 minReplicas: 2
 maxReplicas: 5
 targetCPUUtilizationPercentage: 80