apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-webapp1
  namespace: rezapoc1
spec:
 scaleTargetRef:
   apiVersion: "apps/v1"
   kind: Deployment
   name: webapp1-deployment
 minReplicas: 1
 maxReplicas: 3
 metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80