apiVersion: v1
kind: LimitRange
metadata:
  name: compute-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      Cpu: 200m
      memory:1000Mib   
    defaultRequest: # this section defines default requests
      cpu: 100m
      memory:500Mib
    max: # max and min define the limit range
      cpu: 300m
      memory:1000Mib
    min:
      cpu: 100m
      memory:200Mib
    type: Container
