apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.122.10 - 192.168.122.50
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advippool
  namespace: metallb-system

  