apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  # IP from the NAT default network on the system
  - 192.168.70.10 - 192.168.70.50
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advippool
  namespace: metallb-system

  