apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  # For Linux make sure to choose the IP from the NAT default network
  - 192.168.39.50 - 192.168.39.100 
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advippool
  namespace: metallb-system

  