apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rezapoc1
  namespace: rezapoc1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-storageclass